VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "<BOX_NAME>"
  config.vm.synced_folder "shared", "/home/vagrant/shared"
  config.vm.boot_timeout = 600
  config.vm.network :forwarded_port, guest: 80, host: <PORT_GEN_HOST>
  config.vm.network :forwarded_port, guest: 3000, host: <PORT_RAILS_HOST>
  config.vm.network :forwarded_port, guest: 5432, host: <PORT_PG_HOST>
end
